name: Android CI (Debug)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 3. Устанавливаем Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      # 4. Делаем gradlew исполняемым
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      # 5. Сборка APK (Debug)
      - name: Gradle build
        run: ./gradlew :app:assembleDebug

      # 6. Загружаем собранный APK как артефакт
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kizzy-debug-apk
          path: app/build/outputs/apk/debug/*.apk
